version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    environment:
      - NODE_ENV
    ports:
      - "3020:3020"
